accounts/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from accounts import views

urlpatterns = [url(r"^send_login_email", views.send_login_email)]

lists/urls.py
# -*- coding: utf-8 -*-
"""superlists URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import url

from lists import views

urlpatterns = [
    url(r"^new$", views.new_list, name="new_list"),
    url(r"^(\d+)/$", views.view_list, name="view_list"),
]

superlists/urls.py
# -*- coding: utf-8 -*-
"""superlists URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.conf.urls import include
from django.conf.urls import url

from accounts import urls as account_urls
from lists import urls as list_urls
from lists import views as list_views

urlpatterns = [
    url(r"^$", list_views.home_page, name="home"),
    url(r"^lists/", include(list_urls)),
    url(r"^accounts/", include(account_urls)),
]

accounts/models.py
# -*- coding: utf-8 -*-
import uuid

from django.db import models
from django.utils import timezone

# Create your models here.


class User(models.Model):
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = "email"
    is_anonymous = False
    is_authenticated = True


class Token(models.Model):
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)

lists/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import DO_NOTHING
from django.urls import reverse

# Create your models here.
class List(models.Model):
    def get_absolute_url(self):
        return reverse("view_list", args=[self.id])


class Item(models.Model):
    text = models.TextField(default="")
    list = models.ForeignKey(List, default=None, on_delete=DO_NOTHING)

    class Meta:
        ordering = ("id",)
        unique_together = ("list", "text")

    def __str__(self):
        return self.text

lists/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError

from lists.models import Item

EMPTY_ITEM_ERROR = "Oops! You Can't Have an Empty List Item!"
DUPLICATE_ITEM_ERROR = "Oops, You Already Have This In Your List!"


class ItemForm(forms.models.ModelForm):
    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.fields.TextInput(
                attrs={
                    "placeholder": "Enter a to-do item",
                    "class": "form-control input-lg",
                }
            )
        }
        error_messages = {"text": {"required": EMPTY_ITEM_ERROR}}


class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {"text": [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

accounts/views.py
# -*- coding: utf-8 -*-
from django.core.mail import send_mail
from django.shortcuts import redirect

# Create your views here.


def send_login_email(request):
    email = request.POST["email"]
    send_mail(
        "Your login link for Cam's To Do Lists",
        "Body Text",
        "noreply@CamsToDo",
        [email],
    )
    return redirect("/")

lists/views.py
# -*- coding: utf-8 -*-
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.html import escape

from lists.forms import EMPTY_ITEM_ERROR
from lists.forms import ExistingListItemForm
from lists.forms import ItemForm
from lists.models import Item
from lists.models import List


# Create your views here.
def home_page(request):
    return render(request, "home.html", {"form": ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    if request.method == "POST":
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect(list_)
    return render(request, "list.html", {"list": list_, "form": form})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, "home.html", {"form": form})

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device.width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href='/static/base.css' rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Exo:200" rel="stylesheet">
  </head>

  <body>
    <div class="container">

    <nav class="navbar navbar-default" role="nvaigation">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Superlists</a>
            <form class="navbar-form navbar-right" method="POST" action="#">
                <span>Enter email to log in:</span>
                <input class="form-control" name="email" type="text" />
                {% csrf_token %}
            </form>
        </div>
    </nav>

      <div class="row">
        <div class="col-md-12 col-md-offset-3 jumbotron" id="header">
          <div class="text-center">
            <h1>{% block header_text %}{% endblock %}</h1>
            <form method="post" action="{% block form_action %}{% endblock %}">
{#              <input name="item_text" id="id_new_item"#}
{#                class="form-control input-lg"#}
{#                placeholder="Enter a to-do item"/>#}
                {{ form.text }}
              {% csrf_token %}
              {% if form.errors %}
                <div class="form-group has-error">
                  <span class="help-block">{{ form.text.errors }}</span>
                </div>
                {% endif %}
            </form>
          </div>
        </div>
      </div>

      <div class="row" id="table-row">
        <div class="col-md-12 col-md-offset-3">
          {% block table %}
          {% endblock %}
        </div>
      </div>

    </div>
      <!-- Import JQuery JS-->
    <script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>

   <!--Import Hiding errors JS -->
  <script src="../static/list.js"></script>

    <script>
        $(document).ready(function() {
            window.Superlists.initialize();
        });
    </script>

  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
{% block header_text %} Start a new To-Do List{% endblock %}
{% block form_action %}{% url 'new_list' %}{% endblock %}
<!-- <html>
  <head>
    <title>To-Do lists</title>
  </head>
  <body>
    <h1>Start a New To-Do list</h1>

    <form method="post" action="/lists/new">
    <input name="item_text" id="id_new_item" placeholder="Enter a to-do item"/>
    {% csrf_token %}
    </form>
  </body>
</html> -->

lists/templates/list.html
{% extends 'base.html' %}
{% block header_text %}Your To-Do List{% endblock %}
{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}

<table id="id_list_table" class="table">
  {% for item in list.item_set.all %}
      <tr>
          <td>{{ forloop.counter }} {{ item.text }}</td>
      </tr>
  {% endfor %}
</table>

{% endblock %}